import { readFileSync } from "node:fs";
import type { AggregateReport } from "../analyze/report.js";

const fmtN = (n: number): string => n.toLocaleString("en-US");

// Markdown table cell sanitizer. Attacker-controlled tool / rule names could
// otherwise break the table (`|`) or inject raw HTML (`<script>`). Normalize
// whitespace, escape special chars. Clamp length so a 50KB tool name can't
// blow up the PR comment either.
const MAX_CELL_LEN = 200;
const CONTROL_RE = new RegExp("[\\u0000-\\u001f\\u007f]+", "g");
export const escCell = (raw: string): string => {
  let s = String(raw ?? "");
  if (s.length > MAX_CELL_LEN) s = s.slice(0, MAX_CELL_LEN) + "…";
  // Escape backslash FIRST so subsequent escapes don't double-encode.
  s = s.replace(/\\/g, "\\\\");
  // Collapse all ASCII control chars (incl. CR/LF/TAB) so a crafted name
  // can't break out of the row.
  s = s.replace(CONTROL_RE, " ");
  // Escape markdown/HTML specials that could break rendering.
  s = s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\|/g, "\\|")
    .replace(/`/g, "\\`");
  return s;
};

export const formatMarkdown = (report: AggregateReport): string => {
  const t = report.totals;
  const lines: string[] = [];
  const wastePct = t.observed_tokens > 0 ? (t.savings_tokens / t.observed_tokens) * 100 : 0;
  lines.push("## 💸 Tokenomy — token-waste summary");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("|---|---|");
  lines.push(`| Files scanned | ${fmtN(t.files)} |`);
  lines.push(`| Sessions | ${fmtN(t.sessions)} |`);
  lines.push(`| Tool calls | ${fmtN(t.tool_calls)} |`);
  lines.push(`| Tokens observed | ${fmtN(t.observed_tokens)} |`);
  lines.push(`| Tokens saveable | **${fmtN(t.savings_tokens)}** (${wastePct.toFixed(1)}%) |`);
  lines.push(`| USD saveable (est) | **$${t.estimated_usd_saved.toFixed(4)}** |`);
  if (t.redact_matches > 0) {
    lines.push(`| ⚠️ Secret matches | ${fmtN(t.redact_matches)} |`);
  }
  lines.push("");

  if (report.by_rule.length > 0) {
    lines.push("### Savings by rule");
    lines.push("");
    lines.push("| Rule | Tokens saved | Events |");
    lines.push("|---|---:|---:|");
    for (const r of report.by_rule) {
      lines.push(`| ${escCell(r.rule)} | ${fmtN(r.savings_tokens)} | ${fmtN(r.events)} |`);
    }
    lines.push("");
  }

  if (report.by_tool.length > 0) {
    lines.push("### Top tools by observed waste");
    lines.push("");
    lines.push("| Tool | Calls | Observed | Saveable | Waste |");
    lines.push("|---|---:|---:|---:|---:|");
    for (const row of report.by_tool.slice(0, 10)) {
      const waste = row.waste_pct * 100;
      lines.push(
        `| \`${escCell(row.tool)}\` | ${fmtN(row.calls)} | ${fmtN(row.observed_tokens)} | ${fmtN(row.savings_tokens)} | ${waste.toFixed(0)}% |`,
      );
    }
    lines.push("");
  }

  if (report.wasted_probes.length > 0) {
    lines.push("### ⚠️ Wasted-probe incidents");
    lines.push("");
    lines.push("| Tool | Calls | Observed | Window |");
    lines.push("|---|---:|---:|---|");
    for (const p of report.wasted_probes.slice(0, 5)) {
      lines.push(
        `| \`${escCell(p.tool)}\` | ${p.call_count}× | ${fmtN(p.observed_tokens)} | ${escCell(p.first_ts.slice(11, 19))}→${escCell(p.last_ts.slice(11, 19))} |`,
      );
    }
    lines.push("");
  }

  lines.push("<sub>Generated by [Tokenomy](https://github.com/RahulDhiman93/Tokenomy) `tokenomy ci`.</sub>");
  return lines.join("\n") + "\n";
};

export const runCi = (argv: string[]): number => {
  const sub = argv[0];
  if (sub === "format") {
    const inputFlag = argv.find((a) => a.startsWith("--input="));
    const inputPath = inputFlag
      ? inputFlag.slice("--input=".length)
      : argv[argv.indexOf("--input") + 1];
    if (!inputPath) {
      process.stderr.write(`tokenomy ci format: --input=<analyze.json> is required\n`);
      return 1;
    }
    let report: AggregateReport;
    try {
      report = JSON.parse(readFileSync(inputPath, "utf8")) as AggregateReport;
    } catch (e) {
      process.stderr.write(`tokenomy ci format: cannot read ${inputPath}: ${(e as Error).message}\n`);
      return 1;
    }
    process.stdout.write(formatMarkdown(report));
    return 0;
  }
  process.stderr.write(
    "Usage:\n" +
      "  tokenomy ci format --input=<analyze.json>\n" +
      "      Converts `tokenomy analyze --json` output into a PR-ready markdown comment.\n",
  );
  return 1;
};
